name: Design And Protoyping Assignment Tests

on: [push]

jobs:
  jpa-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Test experiment 2
        run: mvn --batch-mode --update-snapshots verify
